Repository Datenschmutz/docs, pull requests merged in 2022-12, with the labels that each got.

#11 Added missing translation
  cheat-sheets/markdown.md
  i18n/de/docusaurus-plugin-content-docs-cheat-sheets/current/markdown.md
Labels: WIP

#12 New GitHub header Logo
  docusaurus.config.js
  src/css/custom.css
Labels: WIP

#18 Add DocSearch
  docusaurus.config.js
  i18n/de/code.json
  src/css/custom.css
  src/css/old.custom.css
  templates/Docs/intro.md
  templates/Docs/tutorial-basics/congratulations.md
Labels: proposal, WIP

#27 Added Fail2ban Tool and Setup Guide
  docs/guides/fail2ban-setup.md
  docs/tools/_category_.json
  docs/tools/fail2ban.md
  i18n/de/docusaurus-plugin-content-docs/current/guides/fail2ban-setup.md
  i18n/de/docusaurus-plugin-content-docs/current/tools/_category_.json
  i18n/de/docusaurus-plugin-content-docs/current/tools/fail2ban.md
Labels: documentation
